## Loconotion Site Configuration File ##
# full .toml configuration example file to showcase all of Loconotion's available settings
# check out https://github.com/toml-lang/toml for more info on the toml format

# name of the folder that the site will be generated in
name = "wfsk"

# the notion.so page to being parsing from. This page will become the index.html
# of the generated site, and loconotion will parse all sub-pages present on the page
page = "https://www.notion.so/wfsk/ShadowKylin-c7f5cf64b83b450387072c1a1e639f20"

# optionally apply notion's dark mode, remove the line below to use the default light mode
theme = "dark"

## Global Site Settings ##
# this [site] table defines override settings for the whole site
# later on we will see how to define settings for a single page
[site]
  ## Custom Meta Tags ##
  # defined as an array of tables (double square brackets)
  # each key in the table maps to an atttribute in the tag
  # the following adds the tag <meta name="title" content="Loconotion Test Site"/>
  [[site.meta]]
  name = "title"
  content = "ShadowKylin | Warframe氏族"
  [[site.meta]]
  name = "description"
  content = "暗影麒麟 - Warframe 游戏全球服中的氏族公会"

  ## Custom Fonts ##
  # you can specify the name of a google font to use on the site - use the font embed name
  # if in doubt select a style on fonts.google.com and navigate to the "embed" tag to 
  # check the name under CSS rules
  # the following table keys controls the font of specific elements:
  #   site: changes the font for the whole page (apart from code blocks) 
  #         but the settings below override it
  #   navbar: site breadcrumbs on the top-left of the page
  #   title: page title (under the icon)
  #   h1: heading blocks, and inline databases' titles
  #   h2: sub-heading blocks
  #   h3: sub-sub-heading blocks
  #   body: non-heading text on the page
  #   code: text inside code blocks
  [site.fonts]
  site = 'Source Han Sans SC'
  navbar = 'Source Han Sans SC'
  title = 'Source Han Sans SC'
  h1 = 'Source Han Sans SC'
  h2 = 'Source Han Sans SC'
  h3 = 'Source Han Sans SC'
  body = 'Source Han Sans SC'
  code = 'Consolas'

  ## Custom Element Injection ##
  # defined as an array of tables [[site.inject]], followed by 'head' or 'body' to set 
  # the injection point, followed by name of the tag to inject
  # each key in the table maps to an atttribute in the tag
  # e.g. the following injects this tag in the <head>:
  #   <link href="favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/> 
  [[site.inject.head.link]]
  rel="icon" 
  sizes="32x32"
  type="image/png"
  href="/ShadowKylin.32x.png"
  
  # the following injects this tag in the in the <body>:
  #   <script src="custom-script.js" type="text/javascript"></script>
  # note that all href / src files are copied to the root of the site folder 
  # regardless of their original path
  [[site.inject.body.script]]
  type="text/javascript"
  src="/site-script.js"

## Individual Page Settings ##
# the [pages] table defines override settings for individual pages, by defining 
# a sub-table named after the page url (or part of the url, but careful about
# not using a string that appears in multiple page urls)
[pages]
  # the following settings will only apply to this page: 
  #   https://www.notion.so/d2fa06f244e64f66880bb0491f58223d
  [pages.7ea4b2156d0f4584b7a1e4006061fe01]
    ## custom slugs ##
    # inside page settings, you can change the url for that page with the 'slug' key
    # e.g. page "/d2fa06f244e64f66880bb0491f58223d" will now map to "/games-list"
    slug = "admin-board"

  # set up pretty slugs and options for the other database pages
  [pages.dabe73e3f3004977b050639a18bf5464]
    slug = "readme"

  [pages.7ee5338f0beb4f929c5ba9178b5acd37]
    slug = "staffs"

  [pages.684efb229f3545f6a43ced57322a6023]
    slug = "afk"

  [pages.ab0742ab45d84f48bbc1e69823eb912f]
    slug = "why-remove"

  [pages.a1af6871cd7c4e1f9fd66571b93c6ddb]
    slug = "man-board"

  [pages.10be148fc58e4579ab2f41431280e9d7]
    slug = "activity"

  [pages.4dee7fc847f94c14a0bcd65c30b47d7e]
    slug = "guide"

  [pages.6e372d39f61345aaa3c9e9726e1c3bba]
    slug = "blog"

  [pages.618c7d61607a44899e84cadfeca8d265]
    slug = "site"

  [pages.7faed6847487401abd3fde5fd9ab1c44]
    slug = "share-mods"

  [pages.29e1b015980d40ae96ef411abeb930f8]
    slug = "share-schemas"

  [pages.7e0a8e7062c947cebc347460c134c64f]
    slug = "share-tutroial"

  [pages.7bb413b1248647e9a80d1f1b08f75bc3]
    slug = "share-ideas"

  [pages.4e166df8983e4c58bae75c6ecdcd85a4]
    slug = "gallery"
