# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CompileSite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build site
      run: |
        python loconotion wfsk.toml
        ls -la
    - name: Append build info
      run: |
        date +%s%3N > ./dist/wfsk/buildtime.txt
        echo "$GITHUB_SHA" > ./dist/wfsk/buildsha.txt
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3.7.3  
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/wfsk
        cname: wf.ckylin.site
